---
- name: Compile SKU_RM0004
  hosts: localhost
  tasks:
    - name: Install build tools
      become: yes
      apt:
        name:
          - make
          - gcc
        state: present
        update_cache: yes

    - name: Clone the repository
      git:
        repo: 'https://github.com/jameswlane/SKU_RM0004'
        dest: /tmp/SKU_RM0004
        version: main

    - name: Compile the project
      command: make
      args:
        chdir: /tmp/SKU_RM0004
